if (!global.strings) {
    global.strings = {
        serviceRequestsHeaderText: "Service Requests",
        allText: "All",
        myRequestsText: "My Requests",
        submitRequestText: "Submit Request",
        cancelText: "Cancel It",
        dueText: "due",
        assetText: "Asset",
        assetNoText: "#",
        createdText: "Created",
        byText: "by",
        toText: "to",
        completedText: "Completed",
        reasonText: "Reason for canceling",
        submitFeedbackText: "Submit Feedback",
        feedbackText: "Feedback",
        moreInfoText: "More Info",
        headerText: "Service Asset Maintenance",
        usernameText: "Username",
        passwordText: "Password",
        loginText: "Login",
        forgottenPasswordText: "Forgotten Password",
        signUpText: "Register",
        usernameOrEmailText: "Username or Email",
        recoverText: "Recover",
        serviceRequestsFilterHeaderText: "Refine Results",
        statusText: "Status",
        maintenanceTypeText: "Maintenance Type",
        dueDateText: "Due Date",
        priorityText: "Priority",
        dateCreatedText: "Date Created",
        dateCompletedText: "Date Completed",
        doneText: "Done",
        resetDate: "Reset",
        sortByText: "Sort By",
        displayNameText: "Display Name",
        emailText: "Email",
        confirmPasswordText: "Confirm Password",
        lowText: "Low",
        mediumText: "Medium",
        highText: "High",
        descriptionText: "Description",
        removeText: "Remove",
        submitText: "Submit",
        submitServiceRequestHeaderText: "New Request",
        shortLowText: "Low",
        shortMediumText: "Med",
        shortHighText: "High",
        dateFormatString: "MMMM dd yyyy",
        selectServiceRequestText: "Select Service Request",
        submittedText: "Submitted",
        assignedText: "Assigned",
        canceledText: "Canceled",
        logoutText: "Logout"
    }
}